-
  name: Run a container on hosts.
  hosts: all
  vars:
    container_name: melihdeneme
    container_image: melihselamiurkmez/dtubuntuimage:v1
  tasks:
    -
      name: Container run
      docker_container:
        name: '{{container_name}}'
        image: '{{container_image}}'
        command: ["sleep","infinity"]
