-
  name: We up the kodekloud websites with ansible
  hosts: target1
  become: yes
  tasks:
    -
      name: 'Install git'
      apt:
        name: git
        state: present
    -
      name: "Clone the repository"
      git:
        repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
        dest: /var/www/html
    -
      name: 'Install FirewallD'
      apt:
        name: firewalld
        state: latest
    -
     name: 'Start the firewalld'
     service:
       name: firewalld
       enabled: yes
       state: started

    -
      name: 'Install MariaDB'
      apt:
        name: mariadb-server

    -
      name: 'Started and enabled the MariaDB'
      service:
        name: mariadb
        enabled: yes
        state: started

    -
      name: 'Configure firewall for Database'
      firewalld:
        permanent: yes
        port: 3306/tcp
        zone: public
        state: enabled
    -
        name: Make sure pymysql is present
        pip:
          name: pymysql
          state: present

    -
       name: 'Create a database'
       community.mysql.mysql_db:
         name: ecomdb
         state: present
         login_unix_socket: /run/mysqld/mysqld.sock

    -
      name: Create database user
      community.mysql.mysql_user:
        name: ecomuser
        password: ecompassword
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

#    - name: Import db-load-script.sql
#      mysql_db:
#        state: import
#        name: ecomdb
#        target: /var/www/html/assets/db-load-script.sql
#        login_unix_socket: /run/mysqld/mysqld.sock

    -
      name: Deploy and Configure Web
      apt:
         name: '{{item}}'
         state: present
      loop:
        - apache2
        - php
        - php-mysql
    -
      name: 'Configure firewall for http service'
      firewalld:
          permanent: yes
          port: 80/tcp
          zone: public
          state: enabled
    -
      name: Configure httpd
      replace:
        path: /etc/apache2/mods-enabled/dir.conf
        regexp: 'DirectoryIndex index.html index.cgi index.pl index.php index.xhtml index.htm'
        replace: 'DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm'
    -
      name: apache2 service enabled and Started
      service:
          name: apache2
          enabled: yes
          state: started
    -
      name: Change DirectoryIndex index.html to DirectoryIndex index.php to make the php page the default page
      replace:
        path: /var/www/html/index.php
        regexp: '172.20.1.101'
        replace: 'localhost'
