-
  name: 'Restart ssh services for all host'
  hosts: all
  tasks:
    -
      name: 'Restart ssh service'
      systemd:
        name: ssh
        state: restarted
    -
        name: 'Restart sshd service'
        systemd:
          name: 'sshd'
          state: restarted
